apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  workspaces:
    - description: |
        This workspace is shared among all the pipeline tasks to read/write common resources
      name: source
  tasks:
    - name: image-build
      timeout: 30m
      retries: 0
      taskRef:
        kind: ClusterTask
        name: alauda-build-image
      workspaces:
        - name: source
          workspace: source
      when: []
      params:
        - name: container-image
          value: build-harbor.alauda.cn/acp/oidc-rbac-proxy
        - name: container-image-tag
          value: $(build.git.version.docker)
        - name: labels
          value:
            - branch=$(build.git.branch.name)
            - commit=$(build.git.lastCommit.id)
    - name: sonarqube-scan
      timeout: 30m
      retries: 0
      taskRef:
        resolver: katanomi.hub
        params:
          - name: kind
            value: task
          - name: name
            value: sonarqube-analysis
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - image-build
        - golangci-lint-v1-a1a64
      when: []
      params:
        - name: server
          value: https://build-sonar.alauda.cn
        - name: scan-flags
          value:
            - sonar.go.coverage.reportPaths=coverage.out
            - sonar.projectKey=gitlab-ce.alauda.cn-container-platform-oidc-rbac-proxy
            - sonar.projectVersion=$(build.git.version.docker)
        - name: quality-gate
          value: "false"
        - name: quality-gate-rules
          value:
            - coverage-delta=10
            - duplication-delta=10
    - name: golangci-lint-v1-a1a64
      timeout: 30m
      retries: 0
      taskRef:
        resolver: katanomi.hub
        params:
          - name: kind
            value: task
          - name: name
            value: golangci-lint-v1
      workspaces:
        - name: source
          workspace: source
      when: []
      params:
        - name: tool-image
          value: registry.alauda.cn:60080/devops/builder-go:1.24
  git:
    options:
      depth: 1
      timeout: 10m
      retries: 0
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 200Mi
  runTemplate:
    spec:
      taskRunSpecs: []
